### ISSUE TITLE
LinterV2 compatibility checklist

### ISSUE THREAD

**Issue by hansonw** [facebook-atom/atom-ide-ui#45]
There are a few missing features from the Linter V2 message API that aren't implemented yet: https://github.com/facebook-atom/atom-ide-ui/blob/master/docs/diagnostics.md#service-apis

- [ ] markdown rendering of description
- [ ] the url and icon fields
- [ ] multiple solutions (only the first one is used)
- [ ] callback-based solutions
- [ ] callback-based description

**Comment by lloiser** [comment]
Is the UI ready so that you accept PRs for markdown rendering of description (without the callback-based description)?

**Comment by matthewwithanm** [comment]
@lloiser You mean for the table? We're ready to accept PRs but I wonder if we really want to allow that to become a dumping ground for random HTML. 🤔

**Comment by Arcanemagus** [comment]
@matthewwithanm The `description` shouldn't be being rendered in the table by default in the first place 😉 (https://github.com/facebook-atom/atom-ide-ui/issues/40).

**Comment by lloiser** [comment]
The main reason for markdown is to allow white spaces in the descriptions to nicely aligned error descriptions across multiple lines. Examples:
* https://github.com/AtomLinter/linter-eslint/blob/7f791653480ce30c1ffe9ab99c6c84e34fe7e7fe/src/helpers.js#L179
* https://github.com/steelbrain/flow-ide/blob/c49dc1c6877e0737e8808e542cb09d16a4fbd399/lib/helpers-linter.js#L182

Further info from an issue in the [`linter`](https://github.com/steelbrain/linter) package: https://github.com/steelbrain/linter/issues/1389

On top of that [`flow-ide`](https://github.com/steelbrain/flow-ide) for example actually uses markdown to render links into the description to jump to files/lines that are mentioned in the description of flow error messages:
https://github.com/steelbrain/flow-ide/blob/c49dc1c6877e0737e8808e542cb09d16a4fbd399/lib/helpers-linter.js#L12-L32
It creates links to `atom://linter` which are handled by the `linter-ui-default` package here:
https://github.com/steelbrain/linter-ui-default/blob/f93b38c7c34e0bbce20ddb82db282295c3ee0685/lib/tooltip/message.js#L86-L103
